# Generated by Django 3.1.2 on 2020-10-12 03:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
